### ISSUE TITLE
Redis::CannotConnectError in resque:work

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#195]
## Error in ULAB Website

**Redis::CannotConnectError** in **resque:work**
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Original Exception (Redis::CannotConnectError): Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
  /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:362:in `rescue in establish_connection'  
/app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:343:in `establish_connection'  
/app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:106:in `block in connect'  
/app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:306:in `with_reconnect'  
/app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:105:in `connect'  
/app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:381:in `ensure_connected'  
/app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:231:in `block in process'  
/app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:319:in `logging'  
/app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/...

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/5cf7d3ecfd294b0019de70eb?event_id=5cf7d3ec003f273d102f0000&i=gh&m=ci)

## Stacktrace

    bin/bundle:107 - load
    bin/bundle:107 - <main>

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/5cf7d3ecfd294b0019de70eb?event_id=5cf7d3ec003f273d102f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by jmalcic** [comment]
Closing as Resque no longer used.
